# Generated by Django 5.1.1 on 2025-02-19 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('images1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('images2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('images3', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('product_status', models.BooleanField(default=True)),
                ('art_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category_app.art')),
                ('paint_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category_app.paint')),
            ],
        ),
    ]
