# Generated by Django 5.1.1 on 2025-02-19 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=20, unique=True)),
                ('percentage', models.DecimalField(decimal_places=0, max_digits=5)),
                ('expiry_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Coupon_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Coupon_user', to=settings.AUTH_USER_MODEL)),
                ('coupon_used', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Coupon_user', to='coupon_app.coupons')),
            ],
        ),
    ]
